# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'sdkv2.0.0' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'ObjectMapper', '~> 1.1'
pod 'RealmSwift'
pod 'KeychainSwift', '~> 3.0'
pod 'OHHTTPStubs'
pod 'OHHTTPStubs/Swift'

end

target 'sdkv2.0.0Tests' do
    
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'

end

